### ISSUE TITLE
add a college name in data/allEngineeringColleges.json

### ISSUE THREAD

**Issue by SanskritiGupta05** [Clueless-Community/collegeAPI#146]
### What would you like to share?

I'd like to add a college name in allEngineeringColleges.json file in the data Folder.
please assign this issue to me.

**Comment by nikhil25803** [comment]
Hey @SanskritiGupta05, we do not add colleges that are not listed by NIRF, also can't accept this because according to the PR/MR policy of Hactoberfest, repos that encourage simplistic PR/MRS (like adding a name or profile to a list or arbitrarily curating content) will be excluded from Hacktoberfest.

Hope to see some quality changes from your side next time. Remember: quantity is fun, and quality is key.

**Comment by SanskritiGupta05** [comment]
Sure, I absolutely agree that quality is more important. That's why I wanted to add it, as it will eventually improve the dataset. No worries, I'll try to contribute in other ways. Thanks for replying! 😊

**Comment by nikhil25803** [comment]
Yes, the college names will get refreshed once the respective Python files will run anyway, so populating it won't make a change.
